runmode: debug               # 开发模式, debug, release, test
port: 9000                   # 绑定的端口
url: localhost:9000          # 暴露的 tcp 地址，ip:port
type: tcp                    # netWork 类型
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/experiment.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_experiment_judge
  addr: 127.0.0.1:3306
  host: 127.0.0.1
  username: root
  password: 123456
api_server_db:
  name: db_experiment
  addr: 127.0.0.1:3306
  username: root
  password: 123456
gormlog: true
data_scour: data
mq:
  kafka:
    brokers:
      - 127.0.0.1:9092
      - 127.0.0.1:9093
  consumer:
    answer: answer_consumer
    problem: problem_consumer
redis:
  addr: 127.0.0.1:6739
  password: experiment